### ISSUE TITLE
Change the label for the TTM Indicator

### ISSUE THREAD

**Issue by daniehughes** [denniskuzminer/algos#10]
For records that have the TTM Squeeze On = True, change the label to the following:

- NormalSqueeze = if TTM_Squeeze(close, 20, 1.5, 2.0, 1.0)
- AggroSqueeze = if TTM_Squeeze(close, 20, 2.0, 2.0, 1.0)
- SlowSqueeze = if TTM_Squeeze(close, 20, 1.0, 2.0, 1.0)

**Comment by denniskuzminer** [comment]
What are the parameters of this function? TTM_Squeeze(close, 20, 1.5, 2.0, 1.0)

Is this from the ThinkOrSwim function?

**Comment by denniskuzminer** [comment]
https://tlc.thinkorswim.com/center/reference/Tech-Indicators/studies-library/T-U/TTM-Squeeze

Make TTM a function
