### ISSUE TITLE
Parabolic SAR Trend

### ISSUE THREAD

**Issue by daniehughes** [denniskuzminer/algos#11]
Add a column called Parabolic SAR Trend

If Parabolic SAR <= Close then "Bullish" Else "Bearish"

**Comment by denniskuzminer** [comment]
If the eventual goal of this data is to run some machine learning algorithms on it, would it make sense to just keep boolean columns (columns where the value of a record could be one of two choices like "Yes or No" or "Bullish or Bearish") as "True or False"? This would standardize things, make the program run faster, and could make it a little easier for the ML algorithms by not having to convert this categorical data. I'm not entirely sure about the last one, but it is definitely true for the first two.  

Yes. Make it a boolean True/False.
