### ISSUE TITLE
Add Balance of Power (BOP) Indicator

### ISSUE THREAD

**Issue by daniehughes** [denniskuzminer/algos#12]
Please add this indicator to our data set.

**Comment by denniskuzminer** [comment]
The smooth_periods parameter is set to 14 by default. Would you want the same or to change it?

**Comment by daniehughes** [comment]
Can you talk now?


From: denniskuzminer ***@***.***>
Date: Friday, September 2, 2022 at 3:18 PM
To: denniskuzminer/algos ***@***.***>
Cc: daniehughes ***@***.***>, Author ***@***.***>
Subject: Re: [denniskuzminer/algos] Add Balance of Power (BOP) Indicator (Issue #12)

The smooth_periods parameter is set to 14 by default. Would you want the same or to change it?
