### ISSUE TITLE
Add 3 Higher Timeframe Market Pulse Columns

### ISSUE THREAD

**Issue by daniehughes** [denniskuzminer/algos#4]
For the 15 min market data, create 3 new columns to show what the higher timeframe market pulse (trend) is.  The higher frame times should be the following:

- Market Pulse - 1 Hr
- Market Pulse - 4 hr
- Market Pulse - Daily

This will show us what the overall trend is in the market for the particular symbol.

**Comment by denniskuzminer** [comment]
Would we be referencing data from other timeframes like this frequently? Because if we are, then maybe I should consolidate each ticker's data for all timeframes into one file, but have a column specifying which timeframe each particular row belongs to. What do you think? 

Yes
