### ISSUE TITLE
Price to EMA Var. %

### ISSUE THREAD

**Issue by daniehughes** [denniskuzminer/algos#9]
The purpose of this measure is to show the distance between Price and the EMA in a variance % format.  Create a separate column for each of the following:

Price to 8 EMA Var. % - (Close-[8 EMA]) / Close)
Price to 13 EMA Var. % - (sum([Close])-[13 EMA]) / sum([Close])
Price to 21 EMA Var. % - (sum([Close])-[21 EMA]) / sum([Close])
Price to 34 EMA Var. % - (sum([Close])-[34 EMA]) / sum([Close])
Price to 50 EMA Var. % - (sum([Close])-[50 EMA]) / sum([Close])
Price to 200 EMA Var. % - (sum([Close])-[200 EMA]) / sum([Close])

**Comment by denniskuzminer** [comment]
(Close-[X EMA]) / Close)
